ALTER TYPE "Role" ADD VALUE IF NOT EXISTS 'SUPER_ADMIN' BEFORE 'ADMIN';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ADMIN_PROMOTED';
ALTER TYPE "AdminActionType" ADD VALUE IF NOT EXISTS 'ADMIN_DEMOTED';
